version: '3.4'

services:
  webapi:
    image: robocoool/sudoku-game
    build:
      context: .
      platforms:
        #- "linux/arm64"
        - "linux/amd64"
      dockerfile: WebApi/Dockerfile
      target: final
      
