# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  webapi:
    build:
      context: "C:\\Users\\Coool\\Projects\\dotNet\\Sudoku-game.API"
      dockerfile: "WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WebApi.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "webapi:dev"
    ports: []
    volumes:
    #- "C:\\Users\\Coool\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\Coool\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Coool\\Projects\\dotNet\\Sudoku-game.API\\WebApi:/app:rw"
    - "C:\\Users\\Coool\\Projects\\dotNet\\Sudoku-game.API:/src:rw"
    working_dir: "/app"
